### ISSUE TITLE
"Cannot find module" error on docker-compose

### ISSUE THREAD

**Issue by dherik** [ResultadosDigitais/matrix#198]
Hi!

I'm receiving the follow error when trying to start the matrix:

```
Recreating matrix_web_1 ... done
Attaching to matrix_web_1
web_1  | 
web_1  | > matrix-backend@ start-backend /var/app/backend
web_1  | > NODE_ENV=production node ./dist/index.js
web_1  | 
web_1  | internal/modules/cjs/loader.js:638
web_1  |     throw err;
web_1  |     ^
web_1  | 
web_1  | Error: Cannot find module '/var/app/backend/dist/index.js'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
web_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
web_1  |     at startup (internal/bootstrap/node.js:283:19)
web_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! matrix-backend@ start-backend: `NODE_ENV=production node ./dist/index.js`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR! 
web_1  | npm ERR! Failed at the matrix-backend@ start-backend script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

### Steps to Reproduce

I changed the `docker-compose.yml` file to add the environments variables, like:

```
version: '3'
services:
  web:
    environment:
      GOOGLE_CREDENTIAL: '565689845454-asdas8789asdjasjkdhop.apps.googleusercontent.com'
      ENFORCE_SSL: 'true'
      ROOMS_DATA: '[{"id": "4bc05520-32a2-42ea-9c24-138f154e6c11", "name": "Lounge", "disableMeeting":true}, {"id": "4bc05520-32a2-42ea-9c24-138f154e6c12", "name": "WAR ROOM CDP"}, {"id": "4bc05520-32a2-42ea-9c24-138f154e6c13", "name": "Data Services"}]'
      ROOMS_SOURCE: 'ENVIRONMENT'
    working_dir: /var/app
    ports:
     - '8080:8080'
    volumes:
      - .:/var/app
    # entrypoint: 'sh /docker-entrypoint.sh npm run start'
    build:
      context: ./
```

I'm trying to start the matrix using docker-compose:

    docker-compose up

This error not changed with the environment variables setted or not.

I also added a `RUN` command to see what is inside the `/var/app/backend/dist/` in the Dockerfile:

```
Step 11/13 : RUN ls /var/app/backend/dist/
 ---> Running in 0da97a5b0d20
app.config.js
app.routes.js
app.server.js
controllers
index.js
office.factory.js
office.socket.js
```

The index.js file is there.

What I'm doing wrong here?

**Comment by juliemar** [comment]
hi, 
Thanks for the report. I just fixed this issue in this PR https://github.com/ResultadosDigitais/matrix/pull/199/files Could you try again using the PR branch?

**Comment by dherik** [comment]
Hi @juliemar , thank you for the quick answer. Sadly, I receive exactly same using the branch `fix-Dockerfile`.

A friend was able to start removing the `volumes` section and I can confirm that adjust work, but partially. If I add the `environment` section, the app seems to start but he uses a weird ip.

For example, without the `environment` and `volumes`, the log is:

```
Recreating matrix_web_1 ... done
Attaching to matrix_web_1
web_1  | 
web_1  | > matrix-backend@ start-backend /var/app/backend
web_1  | > NODE_ENV=production node ./dist/index.js
web_1  | 
web_1  | Running on http://0.0.0.0:8080
web_1  | [ { id: '44251032-cf32-4fd0-82be-1f02225455b6',
web_1  |     name: 'The Dock',
web_1  |     disableMeeting: true },
web_1  |   { id: '8463e140-2cf0-4907-b890-782e023adc11',
web_1  |     name: 'Nebuchadnezzar' },
web_1  |   { id: 'fcf9d15e-c148-4a55-8731-9eead76c48db', name: 'Logos' },
web_1  |   { id: '0b1e972b-9cd9-466f-a641-a528142d28d2', name: 'Osiris' },
web_1  |   { id: '9c2d4c6f-38bb-4f1e-b096-63d983731ad4', name: 'Icarus' },
web_1  |   { id: 'de3b2995-e684-44fb-b4e4-5389dcf06aa8', name: 'Caduceus' },
web_1  |   { id: '454dbe7c-d26d-4b97-8cc8-c1d046f64882', name: 'Brahma' },
web_1  |   { id: '6a9cdeac-8d85-4f1c-8aef-61e4dcb1bfe3', name: 'Novalis' },
web_1  |   { id: '8ef54cae-26df-47fa-b069-11d7de17b006', name: 'Vigilant' },
web_1  |   { id: 'e523944a-d30b-4b2e-a6ae-daf079011629', name: 'Zion' } ]
```

With `environment` variables and without  `volumes` on docker-compose.yml, the log is:

```
Recreating matrix_web_1 ... done
Attaching to matrix_web_1
web_1  | 
web_1  | > matrix-backend@ start-backend /var/app/backend
web_1  | > NODE_ENV=production node ./dist/index.js
web_1  | 
web_1  | Running on http://0.0.0.0:8080
web_1  | [ { id: '4bc05520-32a2-42ea-9c24-138f154e6c11',
web_1  |     name: 'Lounge',
web_1  |     disableMeeting: true },
web_1  |   { id: '4bc05520-32a2-42ea-9c24-138f154e6c12',
web_1  |     name: 'WAR ROOM CDP' },
web_1  |   { id: '4bc05520-32a2-42ea-9c24-138f154e6c13',
web_1  |     name: 'Data Services' } ]
```

**Comment by ramnasidharta** [comment]
I'm very interested in trying Matrix and maybe suggest it to our team here, although I'm still with the same problem.

**Comment by juliemar** [comment]
@ramnasidharta in the file `docker-compose.yml` remove the instruction `volumes`. Your file needs to be like this.

```
version: '3'
services:
  web:
    env_file:
      - variables.env
    working_dir: /var/app
    ports:
     - '8080:8080'
    build:
      context: ./
```

After changing the file you need to run `docker build .` and after `docker-compose up`.

Please let me know if this instruction worked for you.

If yes I'm considering create 2 files one for development and another for the tests.
